# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - medial-ai-staging-web-app

on:
  push:
    branches:
      - staging
    paths:
      - 'web-app/**'  # Trigger the workflow only if files in the web-app directory change
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://medialcontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d8d0dc6f09248f0822781ebd0f1c2ee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ad3576a0210a4bc29855ecf84cc0e523 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: medialcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d8d0dc6f09248f0822781ebd0f1c2ee }}/staging:${{ github.sha }}
        file: web-app/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'medial-ai-staging-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cd810e3c6c71440aab2bdd62dcdb953c }}
        images: 'medialcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d8d0dc6f09248f0822781ebd0f1c2ee }}/staging:${{ github.sha }}'
